# NUMPY

Numpy è una libreria che serve per gestire i vettori in modo efficiente. Possono essere:
- **MONODIMENSIONALI** : come un vettore

- **BIDIMENSIONALE** : come una matrice

- **MULTIDIMENSIONALI** : come i *tensori*

e così via

in mumpy si parla di ND-array _Multi Dimensional Array_

Ogni dimensione è un **ASSE**.

es = [[[1,2],[3,4],[4,5]], [[6,7],[8,9],[10,10]]] ha **forma = 2,3,2**. La **forma** indica in numero di elementi per dimensione.

> Numpy è necessario perchè in python le liste occupano uno sfracco di memoria, e sono inefficienti. Devo memorizzare troppe 
> infromazioni. Gli array di Numpy invece sono a dimensione fissa e devono essere tutti dello stesso tipo.

Array di numpy:
- sono immutabili
- devono avere lo stesso tipo

Tipi di Numpy:
- **bool**
- **int** 
- **uint**: (unsigned int), quelli senza segno
- **float**
- **datetime64** data e ora a partire dal 1-1-1970
- **string**
- **object**

In [1]:
import numpy as np

a1 = np.array((1,2,3))           #array da tupla
a2 = np.array([1,2,3], float)    #array da lista con specifica del tipo
a3 = np.arange(10, dtype=float)  #crea numeri [0,9), dtype specifica il tipo
a4 = np.arange(4,10,2)           #crea numeri [4,10), con passo di 2
a5 = np.linspace(0,10,5)         #crea numeri da 0 a 10, con numeri equamente distanti l'uno dall'altro

print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

[1 2 3]
[1. 2. 3.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[4 6 8]
[ 0.   2.5  5.   7.5 10. ]


In [2]:
a6 = np.zeros(5, dtype = np.uint)       #array di 0 con specifica di tipo
a7 = np.ones(5)                          #array di 1 con defaultfloat64
a8 = np.zeros((2,3))                      #array di 0 con specifica di tipo

print(a6)
print(a7)
print(a8)

a8.fill(3)

print(a8)

[0 0 0 0 0]
[1. 1. 1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [4]:
mat1 = np.rand(2,3)                         #matrice 2x3 di valori casuali reali [0,1]
mat2 = np.randn(2,3)                        #matrice 2x3 di valori casuali reali [-1,1]
mat3 = np.random.randint(1,7, size = (2,3))

print(mat1)
print(mat2)
print(mat3)

AttributeError: module 'numpy' has no attribute 'rand'

# Distribuzioe gaussiana dei numeri o normale
Se utilizzo la funziona randn() avrò una distribuzione maggiore sullo zero. 
## DEVIAZIONE STANDARD


In [5]:
ndarray = np.array([[[1,2],[10,20],[100,200]]])
print(ndarray)
#dimensione di 3
#elementi totali 6
#elementi per ogni dimensione [1,3,2]
#tipo = ndarray.dtype

array1 = ndarray.flatten() #fa una copra corrispondente ad una dimensione
array2 = ndarray.ravel()   #mantiene un riferimento all'array

arra1[1] = 0
array2[0] = 0
print(array1); print(array2);
print(ndarray)

#possiamo modificare le dimensioni purchè siano compatibili

array1.shape(3,2)      #modifica la struttura (3 righe e due colonne)
print(array1)
mat = ndarray.reshape(2,-1)          #con -1 calcola in automatico il numero di elementi per riga
print(mat)

#se devo cambiare le righe con le colonne uso la funziona transpose()

m = np.arange(24)             #vettore con elementi da 0 a 23
m = m.reshape(4,6)            #avrà 4 righe e sei colonne

print(m)

#se voglio fare uno shift uso il metodo roll(): fa uno shift a destra a partire dall'indici indicato

print(np.roll(m,2))       #dall'indice 2 inizia a dare lo shift
print(np.roll(m, 1, axis = 0))    #shift delle intere righe 
print(np.roll(m, -1, axis = 1))   #shift per intere colonne



[[[  1   2]
  [ 10  20]
  [100 200]]]


NameError: name 'arra1' is not defined

In [ ]:
a = np.arange(12)
a = a.reshape(4,-1)

print(a)

ls = a.tolist()     #restituisce la lista python corrispondente all'array

a[1, 2] = -1
ls[1][2] = -2      #anche in numpy si può utilizzare questa funzione, ma è meno efficiente
print(a[1])
print(ls[1])