# Esercizio 1:

In [9]:
#disegnare una scacchiera 8x8 alternando 0 e 1 (la prima casella è 0)
import numpy as np

COLS = 8
ROWS = 8

matrix = np.arange(ROWS*COLS)

matrix[matrix % 2 == 0] = 0
matrix[matrix % 2 != 0] = 1

matrix = matrix.reshape(8,-1)

for index,line in enumerate(matrix):     #non so come trovare un metodo più veloce per alternare le caselle
    if index % 2 == 0:
        matrix[index] = np.roll(matrix[index],1) 

print(matrix)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### Gli altri esercizi non sono riuscito a farli


In [1]:
def x(n):
    if n <= 0:
        return 0
    else:
        return 1 + y(n-2)
    
def y(n):
    if n <= 0:
        return 0
    else:
        return 2 + x(n-3)
    
print(y(100))

60
