In [2]:
import numpy as np

a1 = np.arange(12).reshape(3,4)
a2 = np.array([[0,10,20,30]])   # shape = (1,4)
a3 = np.array([[0],[10],[20]])  # shape = (3,1)
print("a1\n", a1)
print("a2\n", a2)
print("a3\n", a3)
print("----------------------------------")
print("shape(3,4) + scalare:\n", a1 + 10)
print("shape(3,4) + shape(1,4):\n", a1 + a2)
print("shape(3,4) + shape(3,1):\n", a1 + a3)
print("shape(1,4) + shape(3,1):\n", a2 + a3)

"""


Pertanto possiamo dire che due array sono compatibili per il broadcasting se:

    hanno la stessa forma
    hanno lo stesso numero di dimensioni e la 'lunghezza' di ogni dimensione o è uguale o è 1
    hanno un numero diverso di dimensioni, ma l'array che ne ha meno soddisfa la condizione precedente aggiungendo sufficienti dimensione di lunghezza 1 a sinistra dello shape di partenza

Quando il broadcasting è possibile l'array che ha una dimensione = 1, viene modificato in modo che abbia forma compatibile con l'altro e i suoi valori vengono ripetuti lungo quella dimensione e usati per i calcoli. La dimensione dell'array risultato è la maggiore tra le dimensioni degli array di partenza in ciascun asse.

"""

a1
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a2
 [[ 0 10 20 30]]
a3
 [[ 0]
 [10]
 [20]]
----------------------------------
shape(3,4) + scalare:
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
shape(3,4) + shape(1,4):
 [[ 0 11 22 33]
 [ 4 15 26 37]
 [ 8 19 30 41]]
shape(3,4) + shape(3,1):
 [[ 0  1  2  3]
 [14 15 16 17]
 [28 29 30 31]]
shape(1,4) + shape(3,1):
 [[ 0 10 20 30]
 [10 20 30 40]
 [20 30 40 50]]
