# Esercizio 1:

In [9]:
#disegnare una scacchiera 8x8 alternando 0 e 1 (la prima casella è 0)
import numpy as np

COLS = 8
ROWS = 8

matrix = np.arange(ROWS*COLS)

matrix[matrix % 2 == 0] = 0
matrix[matrix % 2 != 0] = 1

matrix = matrix.reshape(8,-1)

for index,line in enumerate(matrix):     #non so come trovare un metodo più veloce per alternare le caselle
    if index % 2 == 0:
        matrix[index] = np.roll(matrix[index],1) 

print(matrix)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


# Esercizio 4:


In [35]:
"""
Nel parco vicino alla sucola e' stata installata una centralina per la 
misurazione del livello di polveri sottili PM10 nell'aria. 
Talvolta la centralina va in uno stato di errore per cui la misruazione 
delle PM10 fallisce ed il dato corrispondente e' di 9999.9. Creare un array 
di 1000 campioni che generino dei valori secondo una distribuzione normale 
con valore medio 19 e varianza 5 e supporre che la centralina sia andata 
in errore 20 volte.
"""

import numpy as np
from numpy import random

ERRORI = 20

dati = np.random.normal(19, 5, 100)
indici = random.randint(100, size = ERRORI)
dati[indici] = 999.9    #9999.9 da problemi di visualizzazioni :'(

print(dati)

[  5.36765733  14.93130069  19.59967787  16.39835164  20.69469911
  31.60938366  22.13237305  14.29776016 999.9         10.6915369
  19.57518589  11.90696827  11.07700349  25.99429103 999.9
  15.67566454 999.9        999.9         25.38844562 999.9
  21.64230637  11.11701699  27.13983662  18.04266303  30.14976678
  20.22323925  17.28916599  17.40354615 999.9         14.35786672
  18.71039733  23.96650555  17.45363129  17.00626239  16.5412169
   7.63522854  19.52223377  11.50977349 999.9         23.93493553
  16.29583489  15.14475241  13.0330648   20.24641746  20.2932096
  19.09945562  21.57339838  30.79335134  18.37500414  22.78252987
  16.81575004  20.02044883  19.85930203 999.9        999.9
 999.9         11.29100389  27.56319941  17.59671959  20.68907437
 999.9         24.26326028   8.9085901   12.88702865  24.28354756
  24.28495468 999.9        999.9         12.52571001  15.35050874
  15.55926805  17.89376565  19.55130046  15.31524264  27.62799096
  23.08627614  27.87142201  22.433