# Esercizio 1:

In [1]:
#disegnare una scacchiera 8x8 alternando 0 e 1 (la prima casella è 0)
import numpy as np

COLS = 8
ROWS = 8

matrix = np.arange(ROWS*COLS)

matrix[matrix % 2 == 0] = 0
matrix[matrix % 2 != 0] = 1

matrix = matrix.reshape(8,-1)

for index,line in enumerate(matrix):     #non so come trovare un metodo più veloce per alternare le caselle
    if index % 2 == 0:
        matrix[index] = np.roll(matrix[index],1) 

print(matrix)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


# Esercizio 3:


In [1]:
"""
In una sala cinematigrafica si devono indicare quali posti a 
sedere possono essere usati con sicurezza secondo le regole 
anticovid. GL iaddetti hanno constato che per ogni fila, i posti
alternati sono distanti piu' di un metro, e le file distano un metro.
Indicare i posti usabili sapendo che ci sono 100 posti numerati a 
partire da 1 e ogni fila ha 18 posti (il posto 1 e' utilizzabile)
"""

import numpy as np

POSTI_TOT =  90

posti = np.arange(1,POSTI_TOT+1)
posti = posti.reshape(-1,18)

print(posti.tolist())

[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18], [19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36], [37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54], [55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72], [73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90]]


# Esercizio 4

In [1]:
"""
Nel parco vicino alla sucola e' stata installata una centralina per la 
misurazione del livello di polveri sottili PM10 nell'aria. 
Talvolta la centralina va in uno stato di errore per cui la misruazione 
delle PM10 fallisce ed il dato corrispondente e' di 9999.9. Creare un array 
di 1000 campioni che generino dei valori secondo una distribuzione normale 
con valore medio 19 e varianza 5 e supporre che la centralina sia andata 
in errore 20 volte.
"""

import numpy as np
from numpy import random

ERRORI = 20

dati = np.random.normal(19, 5, 100)
indici = random.randint(100, size = ERRORI)
dati[indici] = 999.9    #9999.9 da problemi di visualizzazioni :'(

print(dati)

[ 10.29403021 999.9         15.08772077   7.48103944  21.94097758
  21.93687923  26.49371329  22.33218331 999.9         18.68122515
  20.89502177  11.39702114  18.07672928  12.52320392  17.66336794
  18.53328795 999.9        999.9         16.08094626  18.78007378
 999.9         18.03999348  22.84030043  16.17098944  15.16314769
 999.9         13.41915272  16.74931442   9.38669832  26.08247374
  14.51408999  12.13987793  21.82642461 999.9        999.9
  16.75506081  11.42983409  23.79183046  14.75968892  23.39788666
  23.16980388  17.41235847  16.61418819 999.9         20.1241404
  22.12014076  20.67549503 999.9         25.00031273  24.22363279
  18.62999834  21.49115945  24.26441868  17.48113054  15.16066231
  10.28075164  17.40600391  13.99240798  12.26560731 999.9
  21.06281229  22.99550454 999.9         17.19545264   5.84717087
  22.50680383  22.7410515   18.48594052  21.84586316  14.46078207
  18.55989002  18.32218052  21.63167418  14.45187183  12.11803635
 999.9         33.0372507