In [4]:
import numpy as np

giorni = 6


a1 = np.random.normal(1.45,0.02,giorni)
a2 = np.random.normal(7.33,2.3,giorni)
a3 = np.random.normal(12.24,4.57,giorni)

print(a1)
print(a2)
print(a3)

[1.43085042 1.41931427 1.46370073 1.47718978 1.4359351  1.44007039]
[ 4.44985389  8.35221405  9.22821028  4.81887028 11.75904687  7.82563847]
[11.32016014  9.99066013 18.0687265  17.00998576  4.38026471 15.0885404 ]


In [21]:
a1r = np.roll(a1,1)
a1r[0] = 0
a2r = np.roll(a2,1)
a2r[0] = 0
a3r = np.roll(a3,1)
a3r[0] = 0

print(a1r)
print(a2r)
print(a3r)

[0.         1.43085042 1.41931427 1.46370073 1.47718978 1.4359351 ]
[ 0.          4.44985389  8.35221405  9.22821028  4.81887028 11.75904687]
[ 0.         11.32016014  9.99066013 18.0687265  17.00998576  4.38026471]


In [50]:
diff1 = ((a1 - a1r)*100)/a1
diff2 = ((a2 - a2r)*100)/a2
diff3 = ((a3 - a3r)*100)/a3

maxs = np.array([np.amax(diff1[1:]),np.amax(diff2[1:]),np.amax(diff3[1:])])
mins = np.array([np.amin(diff1[1:]),np.amin(diff2[1:]),np.amin(diff3[1:])])

print(diff1)
print(diff2)
print(diff3)

print(np.amax(maxs))
print(np.amin(mins))
print(np.where(maxs == np.amax(maxs)))

print(np.where(mins == np.amin(mins)))


[100.          -0.81279758   3.03248204   0.91315635  -2.87301818
   0.28715849]
[100.          46.72246354   9.49259071 -91.50152919  59.01989048
 -50.26309884]
[ 100.          -13.30742898   44.70744723   -6.22423058 -288.33236982
   70.96959285]
70.96959284914779
-288.3323698245157
(array([2], dtype=int64),)
(array([2], dtype=int64),)
