In [3]:
import numpy as np

a = np.random.randint(0,100,(4,4))

a3 = np.arange(10, dtype=float)  #crea numeri [0,9), dtype specifica il tipo
a5 = np.linspace(0,10,5)         #crea numeri da 0 a 10, con numeri equamente distanti l'uno dall'altro


print(a)
print(a3)
print(a5)

[[73 86 35 43]
 [30 54 71 74]
 [42 93 74 76]
 [38 50 61  6]]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 0.   2.5  5.   7.5 10. ]
